[package]
name = "literate_programming"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
walkdir = "2.3"
pulldown-cmark = "0.9"
anyhow = "1.0"
thiserror = "2.0.11"
mockall = "0.13.1"
tempfile = "3.16.0"
